import {
  Grid,
} from "@mui/material";

import { styled } from "@mui/material/styles";
export const CommonGrid2 = styled(Grid)(
  ({
    gap,
    alignItems,
    display,
    justifyContent,
    flexDirection,
    overflowY,
    wordBreak,
    width,
    background,
    padding,
    height,
    scrollStyle,
    cursor,
    borderRadius,
    boxShadow,
    flexWrap,
    scrollBar,
    scrollBarRadius,
    displayBar = "block",
    paddingRight,
    overflowX,
    maxHeight,
    transition,
    right,
    minWidth,
    customStyle,
    opacity,
    flexGrow,
  }) => ({
    flexGrow:flexGrow,
    gap: gap,
    opacity:opacity,
    alignItems: alignItems,
    display: display,
    justifyContent: justifyContent,
    flexDirection: flexDirection,
    overflowY: overflowY,
    overflowX: overflowX,
    wordBreak: wordBreak,
    width: width,
    background: background,
    padding: padding,
    height: height,
    maxHeight: maxHeight,
    cursor: cursor,
    borderRadius: borderRadius,
    boxShadow: boxShadow,
    transition: transition,
    flexWrap: flexWrap,
    minWidth: minWidth,
    right: right,
    ...(scrollStyle && {
      paddingRight: paddingRight,
      "&::-webkit-scrollbar": {
        display: displayBar,
        width: scrollBar || "7px",
        height: scrollBar || "7px",
      },

      "&::-webkit-scrollbar-thumb": {
        background: "#888",
        borderRadius: scrollBarRadius || "0px",
      },
    }),
    ...customStyle,
  })
);
export const CustomDiv = styled("div")(
  ({
    position,
    margin,
    borderRadius,
    boxShadow,
    padding,
    fontSize,
    width,
    fontWeight,
    top,
    textAlign,
    background,
    bottom,
    zIndex,
    transform,
    cursor,
    border,
    height,
    overflowY,
    display,
    color,
    left,
    gap,
    right,
    customStyle,
    maxHeight,
  }) => ({
    cursor: cursor,
    position: position,
    margin: margin,
    borderRadius: borderRadius,
    boxShadow: boxShadow,
    padding: padding,
    fontSize: fontSize,
    width: width,
    fontWeight: fontWeight,
    textAlign: textAlign,
    background: background,
    top: top,
    bottom: bottom,
    zIndex: zIndex,
    transform: transform,
    border: border,
    height: height,
    overflowY: overflowY,
    color: color,
    display: display,
    left: left,
    right: right,
    gap: gap,
    maxHeight: maxHeight,
    ...customStyle,
  })
);